apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  chart:
    spec:
      chart: homarr
      version: '3.14.0'
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: homarr.wc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homarr-tls
          hosts:
            - homarr.wc
    
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        size: 1Gi
        name: "homarr-config"
        claimName: "homarr-config-pvc"