apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  chart:
    spec:
      chart: homarr
      version: '>=0.1.0'
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/ajnart/homarr
      tag: 0.14.2
    
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: homarr.wc
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homarr-tls
          hosts:
            - homarr.wc
    
    persistence:
      config:
        enabled: true
        storageClass: "local-path"
        size: 1Gi