apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: schub
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:bNCNBwaNB2HZGuRQAokTmtwqVIbgVIqNWyaY3wCxRVfKiAaFsDIWuwI4zx9uBuIngSYaoma3x/zd6IU+2ZLWdQaqwSlffkL1RSRKR1ehUQkLWC4i5QznTohaPB5G/fcijFWk82fXa2F2v75dR+lzG7hPAXpF48q7IY/I0vOqepDktYWiJF28GJgF1YpnoT466DZ3AyIuTUBgrwbxpUHSreiqX8AaoKZa4hY=,iv:V1030tAiXg2A2NtkCQdUqXv7GfLdWk7zWJyxopZlUUE=,tag:2EnEu25rCo+r3SYGUcX8cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NWNJek9qNEwwL0hPVjRU
            Tmx6dit2VEFOZFdEaHZhU2lzS3lxcDc5U2pFCjFud0hDemQ3Smk4TC93UXBTRGts
            K01VMG1QdWdqVHR1VUtBZ3huK1RQaWMKLS0tIHFZcFZFMFZjaGVlK09QOFp0cUky
            R1RNUUwxR1ovdkg2VUtzQjFodG5MZlEKNyku4u9ywYaNulyxOE4fuOHCotqmy4oO
            ZZTkhzaG7cRI48IZyU6T/4cDvYMz9GKJCsBc+nhMEnf9Xb1pG55B2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T18:33:49Z"
    mac: ENC[AES256_GCM,data:CbGiRY5pYLOHHQcNdoKtJRiCARw3uJufytLoe9M04KcqcVfpYM5dDG0he6Cq/uMTXWrF6ote9Qf98nVCxlPo4sBJtcgkEV9nShCnN5b3DftlfmY4BLCTqTS0kVAaj8BTDeXgBgaDCg9BwPZss2ZrIDcxy3gCv8gzzEBT/gz0hFI=,iv:DDYdUM0Ws94l3Mj84BgLPJMgjO7iLLNBbjKwbuMqzEc=,tag:/H9DCZgKufOPQVH3JdHztg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
