apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: schub
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson:
        auths:
            ghcr.io:
                username: ENC[AES256_GCM,data:UTwiEVI=,iv:riDonU+Y5nVzlxjeME5+XYFivXAYmh0avTuhyQkAzTA=,tag:VqLmKanyzmmt/Ijrpqdw1g==,type:str]
                password: ENC[AES256_GCM,data:e326t4heMBe35tfCviagAs44UyjGUkMA/TsRk3qbuha0HsMK0TJtEQ==,iv:ZMhR6UIXOWQiVWiCuKfrO56E91Xmu1stAT0e7EUvLHQ=,tag:lzw/XfjvNKdGIlEhxczi+Q==,type:str]
                auth: ENC[AES256_GCM,data:Dz44JJ4Cr3TGPKHyoAcbOt/JI+5/qvq9VQMReWr1feJtsE90I/rQ6nKLa1lcrEaLaxYMYqn6A5p8FgnAbfMqtQ==,iv:wD8df69v5g1kFeefkbkY8t1j7gN6Expu2sNUCzsqKbw=,tag:CNUpx0da626U0rI4DIkYLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaWZBdGk2YitSOUFoM1BN
            TGFiSE02TnJDZWtwNTZmSk53OUpweDI2RGxNCnRVV3d4OEZLalR1VHdRUHNZZE9k
            Znc4QWdTTWRBaGxHRm53aU9NNm91R2MKLS0tIFk1TnlscE8zN3NwT29CYmRONm1P
            OWdaRFI0cjdYNzRVQSt6Q1JlRUtZWlkKsdqmhvnvjA4NzSgmvsEEfl5l5l/ChkYc
            yhmC4zUa0ngfmhEee5Ki11mZaQyS1xMncHo5G/A8Ji/wLCEpaRJnZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T17:58:40Z"
    mac: ENC[AES256_GCM,data:h3m4x1Hi2npH5R7uoGp/psMcVX+bChirBi3agStX6H1nfSa39tVtkg1CUzv7g8VECSioMY3NViZlavF9OBULx5QuElMtZpzHUOHZ+/+AdsnkIy1qm0fssLdc78+RQ9i3XqZHpZJc3uarbqekFVlub57Ti8KXzGKVGQHf7TJdksw=,iv:kdt/lQcSLy47Bi5sfgU42Qzk//TgzcZnL4YictExit0=,tag:ILxTXuN4ouyQlyw+P9VpvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
