apiVersion: v1
kind: Secret
metadata:
    name: schub-secret
    namespace: schub
type: Opaque
stringData:
    VITE_SC_DATA_API: ENC[AES256_GCM,data:kZMBUp6Ri10DWGwzc2HqzXoI0UUuVuSeiftiJw==,iv:f5yf0NsvanGvA1uDJmcEU6EV03ye3JRMNMackuEw98k=,tag:MXS9oelC+aOxwVRddNerrQ==,type:str]
    VITE_HAULER_API: ENC[AES256_GCM,data:rAEknsiT1OK1rAFr4UStKc8q/qaq5+tFQ11S0wNx,iv:uuu4gZgmkcNs98BSHsGW6SItTm24JAXwEYhgJIlMNtc=,tag:uF620BlCBYqkezx/Q30Hcw==,type:str]
    VITE_HAULER_WS: ENC[AES256_GCM,data:W9PSAARVVIt69HHfTOxN4K87OdJdbRVhlLbMaVfdSqMu,iv:M/ShvakWQtth4Nyi3W/FDTQF7H/3Sy0Npjvu99nyz1E=,tag:EpG2R0pWcX5LeNAHhUtcyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SjZYZmo4MmNHdnBRVkdI
            Z2MxLzBmUkxTQ3A5MTJ5cjU2ZmNnd09IQng4CngwNlo5TVYzQjkreUhQaDJTeDBV
            bDZKeldHYlY2MUpja0VjZ0NQVXc1cE0KLS0tIEZRK1V4SGhIUGp2NHBtZ2xSL01t
            N1pnZHptNnNPcU45dTNJTVZacUdKaXMKOGx8aIN2IUTUCGhPhLCbvfeaNkwv32dt
            1JItxOQ9+/fSYDq3TJh1OnbayBUl41yhwaGT5ar0FO8n5tFtHVUmUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T13:25:21Z"
    mac: ENC[AES256_GCM,data:bgNeDgdvhWxf1/1YwhIJuIbLOLESm1LSJg1HL+bXEXtVrfWfdW2982R2dbTKX2dP0+CgbPu0mMYEM8/iVBE4tDmnIHnAfqXrLhZq+TDIpWineooNQoYJRbXK8ZJvN7xwWG5y9W5NOZwEomNy59tkeIdHUVXIgl5QeDUgiv2DYwY=,iv:Ci8pNuhRPTLMh1qEnShcdZMu0sbXXl6wX2UWDw0bDR8=,tag:8Be6nHcGZzwdnCZWBERegA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
