apiVersion: v1
data:
    DB_CLUSTER: ENC[AES256_GCM,data:mJ3Ht6vA9q1AqO4VtbRrtNNtktFXwmxW/q9TJqKc0mUbRZ7Q,iv:QT/kK/nJ00/68YP+YjP5RSmFJOiCqLev4Y5oAHXWH8Q=,tag:Hqa4ZwqmiY0VT7Cdd4Ipbw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:V/tKCu6hdEY=,iv:un4N4s6+m6pWyFXneB4aZA0lxKnLGyMLpw2wW25JNTI=,tag:WMNwBdyrFcIN+sZVV9D5Dg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8D8J9hE98uFLArouI/gy9/8M3/s=,iv:GCkEoHtu+wjXmDpjASsuEP5kJ8+2NIEyzyJGVThnH/U=,tag:7LuMO9DYQ3LwGuHfxaK9aQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:OgoFQ6F5bM4=,iv:utdXNVL8ZBeDnERHInsx9H8KcAYLLs8ePFcMWgiNWgs=,tag:NNzmeaE7kXHUywwKypw2SQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ZF+mCsEY875NZA0sQn07WIqsCxZZpLf0T1rmOAwqnEknEDA3FIGqO+ccvVgpIEP60QdqHmWyjhnPpQ85bDahuGDxPbQau60bZBWwB2sBxEaFwFgNn0gIzQ==,iv:pUy0HManIeyNLtZ1bkOqsfMhHktXrm5kQZFlQGXqr9Q=,tag:LsPjnqttw36RMsh7PGDaYw==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:4y78XKgFAY4xWRNH45QqbtQiTHdYb48HS0dLrco1rx1bTA3VqbzKctm7Ma6XJL0qjAFM2PDvKJQwUc33baUDqhHulPNYgz/002+coPCI7/vwJNAYbQQw3lhQgfzrp7LN6smyzb9kyVYc7n7NpFD6kPhZ1xfEVy3JcTxixUFBenA=,iv:WAtvvN0dG4LkdUyzeLOBd2SvVh6uj4mxJBxIKhbPRW0=,tag:w2BULbf+ZMR1VNdSS4y6pw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:HPkDVCWZt/1D3zpbQ8dPnA==,iv:Zq7NIprX4Z6jlmVrsccdZ/DItOBUdo4QFmn366gbCZc=,tag:+asWu8jEHYXRe6H/lARwnQ==,type:str]
    PORT: ENC[AES256_GCM,data:XraBlny5qY8=,iv:ofLBDqbkiL3PCsiJyAIJZuLG0f0KbHNapkatDd7o9NI=,tag:/4BvItllyKCUd0NtEPi9tQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:t056X6/8SXDf2sJfalQvCf794gyhl8TFsSD4uxRzZzm/IckwL6Arnn0nO51MdJAv7EzVIRTRxx+EkOQkgjgoGPDWY31nTyjLut2SpjDcEmg6qDEEvslyzA==,iv:Aqh5yH0P+DdCvp8GXDiuGO+E6wychxkxXDi7iuc7AcA=,tag:jMkwR36coXxJhzI1HTzgBA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: clearpath-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOW5ZZzEvS29KVTVMVmkz
            aDA1L3NkL0tRTENSUlcrTzVxSHhOd0t6U2hjCk4yYXNuY2RHVUZNbW9JeStpT1VT
            SWVBYkRTQUg5Ui9RYWhPRktIQ0VnckEKLS0tIE9Uem4xRXdxSDVsVEkxQWJFK2dT
            a3BGa0xtcHJYNWROSy95dWJjZ0prc1EK08BmkY4ni6r61hEVrSXvYynhvp7e0RsJ
            yQjRvJBhXJXVS6biKLcd4/bMaYm8+sJuvBgZnrPQlKAEagcIU3YpnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T15:33:53Z"
    mac: ENC[AES256_GCM,data:TgwbkjFU+xsB4UnIyzDaJoU4JEUwZO+sDH14+jfNsdZqlEzTGNMRizWOROwRCHubkwfvIDDoEsYNF3zXHao6YpdaOKNKV1juCvQQh3IEdetdVer6jgqZBh7eWgn3AXYOF22MhC77fEewAw9vUOS78o6oeZX+CxDbBRm/5OsENxs=,iv:8mY3mt8UTn52Jjg8xTYBcsL5wo9rjWUzVbwqWip/aNU=,tag:IvgmmwmqyJaeCO6LpjujKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
