apiVersion: v1
kind: ServiceAccount
metadata:
  name: plane-database-fixer
  namespace: plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: plane
  name: plane-database-fixer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plane-database-fixer
  namespace: plane
subjects:
- kind: ServiceAccount
  name: plane-database-fixer
  namespace: plane
roleRef:
  kind: Role
  name: plane-database-fixer
  apiGroup: rbac.authorization.k8s.io
