apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

patches:
  - target:
      kind: Ingress
      name: plane-ingress
    path: ingress-patch.yaml
