apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Ingress
      name: plane-ingress
      namespace: plane
    path: remove-ingress-class.json
