apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - ingress-fix-rbac.yaml
  - ingress-fix-job.yaml
  - database-fix-rbac.yaml
  - database-fix-job.yaml
