apiVersion: v1
kind: Secret
metadata:
    name: sc-data-secret
    namespace: scdata
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:ECO+UhX+FiKJgnaHDUMihEBJKnopVHD7UbYEaesq3/juIVC2BdHrQaIAsOw3JaPdvmbxFOKSpoOH09Du+Gnmxo2kaUuNdna66ILTdtr7v6umM0OPUxDcazfwyl7qg9J7pQOWerI3jPDxPCMNi46o1cSiLvMgc3/2mJXjhxKJXNw=,iv:UKdPaTJlG5W/bDUfRoBq6hEOfq6grHG83NDSKYW3/+8=,tag:RX+8hZadZn3gvqg5honBag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbWI1alZZQUtzMWYvMmFS
            ajY1MW9EcDhiUWNQVXNYZ21zRUNHVUFPV1dRCk1QZUR5YnhUQUJhelZROVdJWk43
            bktaMjNXS0kzVVZ4U3Y0UVdKZGJPdEkKLS0tIDFNYnA5dGNmRlNJTXlHbmQ1WGNu
            WFY0S1M0eE1YRlhMZnlIWjRKSUZ1WncKmSKCtTxlBpTiFWTmork5aDh/YTemS7dR
            mz/eDACEgU4ccfnpZedAv73ebymMdlmw2pqjWMag+FxB64jFDjs+uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T14:07:43Z"
    mac: ENC[AES256_GCM,data:xQRnuhFtNrMqb2mN3WGZ9lhL8HZ8qJICc9SDiS41JxYSGC1sULrMaC5m5zYMmg4WZ/niS70HRZaK1vvyKV8+1j4szwMgscgYn4OQyTWocEpykZePmGiexxRpVFKP1CaVxNsccTWrz5S+kNohA8pnM6HK84mno3MLGIrUUWfHwQA=,iv:7gpUTlRucg7iR5axsNRPeZ13h0c4C2cdzoLQ0seaEBI=,tag:iP0XclU17Laq8IdUwKYiKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
