apiVersion: v1
kind: Secret
metadata:
    name: sc-data-secret
    namespace: scdata
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:jbhp76CxUmKWqwntYpjGNoxZ2V1mKgkMO9hmthPEIlzTz2Hmg/WQBNAFiGJEp+mSy27UJOFi3Ho3wy2VL2Krt9qqSd+R3Q7J3qJfTD/AJ+gideuGX+PM60XpwGObIZjz2LAGZO4Nn0yUVNaiS555H9InXNf9XlgNNJPipwv7RIjl,iv:g8hngmN44fVEb66lmJ5wRU8PP0QCw0ImDtOtgjtML8A=,tag:T1aro1Yx6YEKhVwy0bCotw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dy9LZW1VNkgxWFloNUFl
            YTJZQk1kVDBtcEFRekF1YUYwVUdyN2xoY1NRCmVraW5jTjVVSnZnNHFCa1piUWY0
            alAxTklYYUtoWEVXWmF4VGZ1djlVWFkKLS0tIEY2eFIzckNQWDNxVjV3SlM5ajNi
            UTl2VS93cGFJcnRhS0k4T0pHNmpQcTAKPWsc4qddglJNKDftYWjiARF4wqNi0I8U
            TIlYK8Y3+UXjNsjo/fJoX7KMxupQU9z15JPdGmNK2zEOdTV2A8yRVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T13:53:02Z"
    mac: ENC[AES256_GCM,data:lZmCGqOhX1J85gLJL2tooi1m7PDo+993pb83myv4Sj/yfrLEbwpRTo0fYRYMldHMy5soN7sV7BqyQn0xW+KHFbGiItid/1k+WKbuvB59LSpQTSLszA1kIEoLcdl8E/XYgea9oRtr9IdYurRHf2NqZZLVQLOgwv5zr4cp0iAHeB0=,iv:KikGZ5mPCnL9gh50AItAguYCN8wE1lyMX3f2+ChzLMI=,tag:SyNnUUCzLzwnx/9ULodhgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
