apiVersion: v1
kind: Secret
metadata:
    name: sc-data-secret
    namespace: scdata
type: Opaque
stringData:
    database-url: ENC[AES256_GCM,data:o5JnHCslMRxfent+jdudsj/R0bje8LxF34pGXE6l9TbSFg0RFP42t8jKY/8GU2LUiVJCqq6ffniztQSBisrW8kFrgqnLUdaNpdbGLpoAyS12MkmPEmSw362dIjk0G0DCzSnXLH3tqsrSn88iSnK2U4lCERcxBqzHRqcAz9zgE+Gg,iv:HyjG95bDhXd1SN1lQ7UWoHuyUVGimAMVJRfBaSZQRmk=,tag:QNfhCLehFIerjSCre6/l5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWUZacU96NFh1QnFKSWNk
            OFFSd1RibFJiRm9ueklnbFV0TFFhSUtQQ21NCnB2aWtja0ZoQzM1VU1GVXIra2Yr
            TVRXd1o3aWVBM09XZUxLbE91cWlZOFkKLS0tIEVVQWFMM2lxdVRKRTdsYlFrQTdx
            NExyaDNvWmxMSExpNnZpSE1ETGdQSW8KT3k3nPOcA+Hjz1B/q2WVdZTJlbf+HaTp
            ZmJHZZqeMr0HjNStV+HN1Q5l+XAOEsCBBaQMDuuQGNflYi/xN2PVMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T14:05:32Z"
    mac: ENC[AES256_GCM,data:GDO2XvefdGJtJU2h0PmPhprRMRYFq8HQY41bnBH3U214oZGeJmqIBvaH+LIKngr77c0jWrc8TsfmsPg79euhDt9SZJ3+pEK96/y+w7xqcQ7kHdnaVGF3c0pV2EqtYfzhRBHV2pFXT1RMIaUsMK8+g6kwYGbwM/ETfOB3T/cv6rE=,iv:N61Fm8KSbJg/+TbAOtAFaa2FBHD1tjHa3ytCjNYRunU=,tag:0jeXlr0Jn13PtWk4myxUCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
