apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sc-data-api
  namespace: flux-system
spec:
  image: ghcr.io/omtut/sc-data-api
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sc-data-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sc-data-api
  filterTags:
    pattern: '^build-(\d+)'
    extract: '$1'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: sc-data-api
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore: update sc-data-api image
        {{range .Updated.Images}}
        - {{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/base/sc_data
    strategy: Setters
