apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mealie-public
  namespace: mealie
spec:
  entryPoints:
    - web-public
  tls:
    secretName: mealie-public-tls
  routes:
    - match: Host(`mealie.hondo-dev.com`)
      kind: Rule
      services:
        - name: mealie-service
          port: 9000
