apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drawio-cert
  namespace: drawio
spec:
  secretName: drawio-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - drawio.wc
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048