apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plane-cert
  namespace: plane
spec:
  secretName: plane-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - plane.wc
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048
