apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-cert
  namespace: mealie
spec:
  secretName: mealie-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - mealie.wc
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048