apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bar-assistant-cert
  namespace: bar-assistant
spec:
  secretName: bar-assistant-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - mixitup.wc
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048
