apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:NdtKjM7lt9Yrhd4gBOmfRtMXPKA5S40g7FK4GQfdfhxkFoVcbZZz95QsGer3OGCTBxmwc+0=,iv:rRYcxA2QfFXLA/I8ueRn0EWcZ/hYYkxrNh891bGFKEA=,tag:CVAzbv0j++fcqkDYJTfaWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdXM0MUZMcHFqWVNFNFNY
            bDg0RVZ0anlveDR3NjIzY3VJajI2ZGRIcURRClpxaDlFVzVoaEYrbDIrc1dERE43
            WDAxMElEOUlnSjkrelZMMVFQbXU0dG8KLS0tICs4LytvSEs3ejZmc1NYNHVBOGhm
            TlVaR2lhcjBFakNqZ1luYkRkVDFoK00KVrPMdCoxvsBSHu0DG+A2J4/7lHn1jLfE
            bGrcxQcgSX0cJqbl1gJm2J5AwXtIl7UlqpzuWjlntynehUBz37CB+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T16:58:00Z"
    mac: ENC[AES256_GCM,data:wtWWCSuuGd8ygdRUyrF3ZG35P8DB85TED3QqilqZzlkvvAVc71aoTVA9IueOwv1PPgfTxgNmK1+3zLhCBvo3qzSwrF7oRjaLs0mEPg20WXwi35TXuAT/jWiNIUuXBS4eBWaUt3j0JRQItt+oXC9KgIk40Y+F5zzgEfhmlTNva/E=,iv:p/9HMQa1Z4EshfO1QXhHlZjTEDsGsZTMNMK3LMdeqXQ=,tag:AmrZdDlVuoOs2aYZqWnMOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
