apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearpath-frontend
  namespace: clearpath
  labels:
    app: clearpath-frontend
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearpath-frontend
  template:
    metadata:
      labels:
        app: clearpath-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/omtut/clearpath-frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://clearpath-backend-service:5000"  # Backend service URL
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
