apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: clearpath
  namespace: clearpath
spec:
  entryPoints:
    - websecure
  tls:
    secretName: clearpath-tls
  routes:
    - match: Host(`clearpath.wc`)
      kind: Rule
      services:
        - name: clearpath-frontend-service
          port: 80
    - match: Host(`clearpath.wc`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: clearpath-backend-service
          port: 5000
