apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bar-assistant-data-pvc
  namespace: bar-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data-pvc
  namespace: bar-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
