apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-db-creds
    namespace: nextcloud
type: Opaque
stringData:
    db-host: ENC[AES256_GCM,data:d5Jzc1dLuYt4FKstFpYZopFXgSEz+EGCJV+9duOqrhLEKYRQKx3Jvct7/Ys8LDDH+5TumiT4OwV/If0JWHubht7M5Ske0Q==,iv:HxbqnMnEtPfiU3ZCFZXf8YECiWUV+GHcK+Xh684hgs8=,tag:yOza96WnKthFkxj/xXHpDQ==,type:str]
    db-name: ENC[AES256_GCM,data:SKi/VeJShCj2,iv:+ekOW5TpDoOmxruSrgkS9EV/hBz5Uykb9Oq601Ni0uQ=,tag:91tg3JOORzFTZf6++SSyhg==,type:str]
    db-user: ENC[AES256_GCM,data:oW/E582vybbv,iv:qPmXtYfMTdpLqihzcOHpIWVwHqgpqhNMXpno61RXOA0=,tag:yu8AoAvItudiW0jjfK9BbQ==,type:str]
    db-password: ENC[AES256_GCM,data:lZgvDhB2msOuhQUBSVH/Jspa,iv:fNWRsjf3Azvsr6yPUnddvw+HbhwaOczLPvDcLDLqj/I=,tag:/p4i4T0yPFzMkUnlGMwTcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0THlGZFpBLzhqL0R5U2pi
            RXpQZ0xiV3VCMlBLYldvT3Q0RVVXQjhpeVIwCkZXbEwza2lEMW5pUGw5QWhvaVlJ
            bHBmUVFyRXJyYU9aV1JGOHUxTGU3SkkKLS0tIE1PcVJYdjhEQ1RadjVTQU1aZDlX
            OE5XV24vOGtOa280RzdheklEZWowMUkKGL9ttzIxkBI4u2YQhyP+vcm3OsxJxWrD
            aeeFuB48ne5Ef2cq8/TEys0gtHk4x7OhTFkXrxjgY+79LSWwLP0GPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T18:40:43Z"
    mac: ENC[AES256_GCM,data:W8sVJ79gsp/1j4l+lLdlkpvgzY2e5XuSVMyPt6bCG/kmQlNuWKqZ2eK39ZJCBpXvZuFK2wxiuiSeStv3PHXfySJ/sCIlAqkJ+JZH6xA/RCb1Cwph6Pxkq+AoFGc/w8CZI8lKqxQJA1kotQx8uYfwi26F9DvL+5k8GFKoMQYW6mY=,iv:QVhRBxsD/pJ8RhdXQsgkKi0GYpABolmKCDWpCKTVGEo=,tag:oHJ06exNuTUfyCEa8Z8k2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
