apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: pgadmin4
  labels:
    app: pgadmin4
spec:
  ports:
    - port: 9080
      protocol: TCP
      targetPort: 80
  selector:
    app: pgadmin4
  type: LoadBalancer
