apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cni-resources
commonLabels:
  app.kubernetes.io/component: networking
  app.kubernetes.io/part-of: infrastructure
resources:
  - kube-flannel.yaml