apiVersion: v1
kind: Secret
metadata:
    name: community-bloom-tunnel-credentials
    namespace: community-bloom
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:5VZjD8J6Hysh15YtoBS5reyxXjvZ8ewD8T6gQQgxsmqoVjUJZR/WQ0t/ZRzfdJnE83GVSyg1lnveFG1EvRS7BMMEr6TZMwAV+PGHgh9UZqMfb3kiNFHktzws3zJggi3nGMfIo3TuVyQlkn0hjs8frzkloeZ5l18zBtD5Dv2T0g7hAsMfo0MODGRwaIqLYSCZ7SMC51VqrzyojG9E2s5hNRI30ED6rgVH8bX9rA==,iv:Yf0Y+kR/+TfQmXxB3izuEXlv//lJkTIhd+HeHBb3HFU=,tag:mH35wTnOr5pX0EgKAxer4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcWprTHAydHRLZSs4MFV3
            d0czYmt4UkVsMnhkYWN0NUgxTmdSQXFZSVdrCmhZMzcwbTgzMlJXYWx1dVppMFdp
            bWM1cGZ2Y0x3RGNIRlVOUVkvRzdZc2sKLS0tIC9tYkFQMVR6UURTbGdyaXhyc1A3
            TGJLdEEzcmxFNFc4UjdmZUtzTzFQV1kK5XKEnpIDTThKU4LyXmbt9gmJYgJo6fjV
            Z3cX4TViv4aNMXIM/mpWM2ZkR2WcNSba6ASzYAosNuv0qqK58ffcMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T16:28:33Z"
    mac: ENC[AES256_GCM,data:y7AVevcRN0J06JYSzVzF+5iimH40I8mvbJW1US77hqGXp/BLGeYvfqPRBqfKB3ieDjuw31mO9/fI86vhrQT+eB7mmGIknI5Ayd752A8B1Y6qpXhMvY7Izfn33nl9/bw62cCy/dre/4x9KrFPLG5ssnP3eu6wc+3DLMmEnUiWUt8=,iv:WfenGVpWda035aa0P9jhTmL2ftdwPxKwu4dOJxiySvg=,tag:pBq5nIVPD9gi6xo+4rv37Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
