apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:i6bjhvGBsjoyO6eI,iv:ou2snLJcxQ4PMcKBtPa7KPL/n14TEPxJKR5afRD8eGU=,tag:1n2gv0F7p+jYKWQ6JI1UUg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Waw0mVqD4EDcTApIM1FJOSE5Um0=,iv:uNsk4ANfr79siU/+J0BAjh7lv8mEg8Yp+uls8H+YvY4=,tag:Sc2EnT9dZhRrbq+bf4TM0w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hxBhZarQjiFGNIBi,iv:tp7x8pNmIhlXdC/f7zdYKAc/s0n01AVfFnG5EGOG964=,tag:SCbV0SZmEqBaVYG0nSoEKg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:oSfRQav+qFTLpT/rCTiFHpz0RjbanMYCEkCKpdKEIr48fdxgUeAjWgDn7pV3YgwuuI+UurY8s52BqUGtp2Fye7AW7sI=,iv:yF6TJnSwSu8/1UgzXImlWTRTgdWtKS7BGyHKhAlmcLI=,tag:nqFEWCjfvsb0fpyksCenXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: plane-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM2RTL3pyOWlSbGJnRUpz
            ZStpVFFKWUlLSUIxWisrYmt5SGh4NWhDY2l3CmRZR25LdVZDVWFubGpBZllLQURp
            bU9nakZFeUFxdjAwLzkwRnJabG40SVkKLS0tIExSemhxU2MzN0FOMmpVLzZITnVJ
            ckdZbGtIZklBRmFJUzVId0h4Q0VIS1kKqBxhHZLoHjWFmLWJcoHihb+SBM0KkfuJ
            MySf0oKVuefw0WGWcv90Lg5PLomfs2EzfiwEJKK8hHux8/fEflU8ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T16:45:38Z"
    mac: ENC[AES256_GCM,data:5L4QBRmW3Nb0SOOZORrCJm8uEPtTVav9wAJK96KAxb9i5VZ1T3p8DlMxF46fx9O93gliSlBPJN3vcrq/CSN/AdjH//GDKNqIeYnmq0M706np6ndNk8vxGJVFlKCCcfsZAJozpxIyQ/BLkwq8JlCZqME8wpzcWUsFE7X2eSW9wrA=,iv:EFWprFHlWPbtQlfXl9ujxNADVijNhzfTn9UEpGMFYg4=,tag:PPu7YZDJTf6flacvzz1p+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
