apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LVNYsL1vy7FNe5rPK7J8f7uDvEiZWf9Mi9TKULFvwojjXWkla3OE3WfXvaTAgKrlomAo4qtZeA5Hj1dtvMg/KiB7FtUVgDp0Opt1qBUCb027APXkdlytGeR0g1FpEVpapu8CYVnae1jPBVs1v/RvumIKxXAGjJO2aGujOXUdEb3seNZJgHQKuFjxFuYmZW0XzN+rNeViNgDiFCjyhzJmyq0fmExGUu8dj0M7Ycyw+pklXYR9/qFhwOXJpr9qF71qnow/Oza9VpnW55w6XhB8AC7IanPAp1hH,iv:xPonpwUF7u0VPgNk+Z+Bgj0a9J9dJ+fm7ybqZl0O0mM=,tag:Ewanp4jDjzRkO4ZSQOb1fQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSjhwM2t1d3kwZ2pjSlhK
            R2pHZFdubDFTMk5tWGt0SGRUSEdSelQ0TXlrCk5yc3o4VGRwODQ5WUN3ckd3aGJQ
            Tm5tMG94eVorajBWZWtVUTdVS2tHODQKLS0tIFVDREFMS0xkTGpnT3htUDA3Rk1N
            MHRib0NqbWdBeWpEQmtKYVZoai9WT3cKgLdYmLEGyuyVHcX1sdSpdXKJeKDwezug
            RVfFf8Xm+wlB9d2NWndF99m4waL3+CTEQrOa6PNAblwNtyhGkXn/HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T20:43:24Z"
    mac: ENC[AES256_GCM,data:x3qol0zRtGUrIp01W26RQ22631YjItb6Ug9LNbbH6+jRcqnBjZeIfHo81iTBKyMhd1kf7jO0aKNI+JFlAss9KJmYTtL9SAyXV0izoU1mmY5pwV4YdWfVTx5+6BgBntLDk2/cRoYgA8Pz2B7CBFVDWM86vHqQLoPbPfDwF57yHMs=,iv:8GzacqybY5hW8rWveHa1d0LklMcmOyYSYQ7/jsex8g4=,tag:FzZZ2cqyVAxopCEBvNa6CA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4