apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-staging
  namespace: linkding
spec:
  description: Postgres cluster for linkding
  instances: 3
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-creds
  

  storage:
    size: 1Gi