apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:/y1TNykDdhUf6cic,iv:f00zO1Mq+hULm+dA1yX+1nufxub3xCNk3oRxmfNRx4I=,tag:wmcvqNwPItRp1241H7J4Mg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BFBHwlc+X0nuoXFB90X8aPwiTHE=,iv:7OaBQ6cp3211l6DkpT8ytskmBOZ+g6azg/tt5kWPYa0=,tag:xpZ+9Kev1qr/2juG3zTHoA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:8z9+cmZXOW1mF5ARAtz3uQ==,iv:kIc70yF9FEJa+t5sgQT8HFjNFEveSKHnueiPZq4Bqzw=,tag:oKb+/jH/Ay92F7s/PPqTBQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ld-psql-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGFQVElRdWlaMTFDSHBE
            ZHdiVGJwdHRYYXJOcXUxMml6ekx3dEhKbUdRClo2aCs4YzJZVVdydXUrNitCOUhX
            bFo1ZFNHc3RUdXoraC9DbTNNT2xOT2cKLS0tIC9hbXRsREhqRVkrWllKVlQ4ME1F
            eDhmTTF2aXp0V1JaRlllQnRhdTRsT0UKqNeZsAeg4HnZE0LmkgMH3t4GUuWenmUq
            m1rtnhO29QtQe/tUqgIiH8819sixJN/MWx47SbfP9VWqrBNlmzNvCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T19:44:39Z"
    mac: ENC[AES256_GCM,data:Y5fmfDoXslqse2GCJane6xUdseQLAOqM8azYgHr0HbEAzGdOTK3NUgdNl7M5bhKKi1/vWDEKXPvmKy0j6Kp/YCPwkhYi1R5luUWcXY6FVVGAzqPYswE2Y+IGQ0KKfnkfMn8iw8swxBiD3L4EpxNHlzjwNTxFWn/aRG0eDKpb4QI=,iv:TaP2RepP/b4PFj/HIrRZed/+RMc2t3ERKhUhYfHOA3w=,tag:GFyreGg1CUFaZosj4vgo3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
