apiVersion: v1
data:
    password: ENC[AES256_GCM,data:0HkSJeT+HXPkZmtyNLvCRw==,iv:MdMLlaVV73P4zYFBELhjMT1Pdavg/xKq2uDRf99lq1A=,tag:OX0opEj3SClCEvoGM5fPzQ==,type:str]
    user: ENC[AES256_GCM,data:KKbVbA==,iv:rPgCXI5S/WqOnLduty7UEuGhoBrwssNEK7G6DeeSRps=,tag:OpugdkNbuxvWXXwgI6O7ow==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR3pCN0tQb0toNnYxbVdF
            TGgxK1pSNEpYYU8yb0d1Z1NMVXc3VmpxRHprCnc1OUVJbTZkU0MzWEVGVmZzajZM
            bkdOQTVUREdHTXNhTGFoSW42YUdHbzAKLS0tIHBEbUxTUTF3dFZlVU50NmVSQ01B
            eW5kNTBxYW1OVEJheEJ5emxpM05URGMKtA1WIWaINPaOxOxMWjYcT7DfKF0QrREi
            ovcP28komf8n4xdnMVVyp8YmF8YICQv0CPqFGEe2yh9e81rG6mXo/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T15:57:27Z"
    mac: ENC[AES256_GCM,data:+LilifZDClGGlbvdMSj/dthzjLicpF90gu9ZApykzgMveY7ijnN69EKhNmn1K2U3PqH08TNGZQV4r4GQo4LUEFuIuV0expPij5aBc1bF/IOJMjUg1D5NB6kv9/aW78HpcdHazZ+o85o2QNzFVtThY0zyZOfcGOYeciMKgv+ENe8=,iv:g1q7A+nXcuCFrvUb2c+qLlTLZy22XD9Q4jQdq2QfBQg=,tag:dzb5ytjRZqbBWnuNR3KFCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4