apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale-ui
  template:
    metadata:
      labels:
        app: headscale-ui
    spec:
      containers:
        - name: headscale-ui
          image: ghcr.io/gurucomputing/headscale-ui:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
            requests:
              memory: "32Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-ui
spec:
  ports:
    - port: 80
  selector:
    app: headscale-ui
  type: ClusterIP
