apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-weylandcorp
  namespace: database-weylandcorp
spec:
  releaseName: postgres-weylandcorp
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.1.7"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: postgres-creds-weylandcorp
    primary:
      persistence:
        enabled: true
        size: 10Gi
      service:
        type: ClusterIP
      metrics:
        enabled: true