apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    service:
      spec:
        externalTrafficPolicy: Local
    ports:
      web-public:
        port: 9443
        expose:
          default: true
        exposedPort: 8443
        protocol: TCP
        tls:
          enabled: true
