apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql
spec:
  instance: 3
  postgresql:
    version: "13"
  storage:
    size: 8Gi
  bootstrap:
    initdb:
      options: "--data-checksums"
  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://my-bucket/path/to/backup
  #     s3Credentials:
  #       accessKeyId:
  #         name: my-s3-credentials
  #         key: accessKeyId
  #       secretAccessKey:
  #         name: my-s3-credentials
  #         key: secretAccessKey
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-psql-secret
          key: password


