apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: database
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.14.0"  # adjust to the desired version
  interval: 5m0s
  values:
    auth:
      existingSecret: database-psql-secret
    persistence:
      enabled: true
      storageClass: "standard"  # change to your storage class if needed
      size: 8Gi
    primary:
      persistence:
        enabled: true
