apiVersion: v1
data:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:Ppv0pkGuBG6Gos9BPVbr2Q==,iv:qaoK1mDKLr6PoS5nnwFU0MljV+xUj00jgTJsWBQhNM8=,tag:faAam85EX/92hqcFgX+UOw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:EV0fye0hKYGBm/rBpoCy2Q==,iv:4Ie/dwLOjGxRRfgvDW3FrNc7kFceUTJdkb5sCq8nDh0=,tag:gUz2dBiKkNrC17VqT4P6eA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pgadmin4-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc1dkZ1lUdmdEazI2OVhF
            a25jUGFkcWpDcnNaZkJFdHBKOU5yNmgvRjNFCnNoTmYwbEZSZ2FGc0Y1ak0xeG00
            a0VRdVA4UjArRjRKdk1JTmM2ZmF5eFkKLS0tIERhaTgyUm5zQVFJT2RDcU1UcTZu
            V3R5RDVVdzlBdHNYQ0dOVmc2VCtSbTAK+TXdWMMXaZLYaZ+fn8nmSFfm90nOuPEh
            WQLI/vy67xl+7hDSzDZryEeU1rVvmSaRNAema4GpKvVdquRVbbUq3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T19:14:04Z"
    mac: ENC[AES256_GCM,data:i9gJ8kCoM0I03aio6X2QiHEeZd9HY9AMaHO6iPsD52RxS8PetzosbkSXgmLm0Xdd1gsOSwupwbzap4MaT5O/VnS2NiAizO2ApkBehx7fGxCICh9+WRPQmT5QjuNO2jB6H1qQQnchXlbHUzdayyxoZ3eUbfRRKjbOdTl2li+wOwc=,iv:TtBGeYVjbSL28QUn9Fd1U1hx9utd8igdtW1YyMh+kWE=,tag:MBmxiwaGd6er+dvv6vKbtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4