apiVersion: v1
kind: Secret
metadata:
    name: njdbot-discord-secret
    namespace: njdbot-discord
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:7k6uihaP0HiGghA3xvQA7B4WFsRw3XeKEERbInSGCEcF0/ADxn+NnqcQCbIki+qAgkoupb7T+vFhUHYcKlxzuH/JKO8l8ZSe,iv:xwnpiBdt71CRttiNVtMY3rufoZbRIqaFMYZYw7JIDwc=,tag:vNEmAG7AKsL695VZcE2dJQ==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:EyHZYjF8NCf3tQ==,iv:jXRj/sxIFZXSpbx2PH0MEMQpSBJOq+KlSlTl00wXFjs=,tag:jDT/K07mSP5gBR2E7jgFng==,type:str]
    PROD_GUILD_ID: ENC[AES256_GCM,data:RB6X8MMtkHH8aD/dDgjGs58O+g==,iv:7fBrZMGyJLby1rlj9SIAw7fcNvo5KqD8K/DmFUWqcWk=,tag:yhnNPU/kmBcatKVaOPTiVA==,type:str]
    PROD_ORG_ADMIN_URL: ENC[AES256_GCM,data:mXXYntcXYGvcI6sVbmN0niZZHfGybHBxANIuNg+X,iv:L4ixpYPxoZFt0N/+h+qkePrI6+Bi1sgt7F9VkGbrlsg=,tag:1uMXORQ1zHknneD6tZoBTg==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:45MkNQ8hTb334cjyE7brtl/IONgvvVbwhR/uxyZAIsumR4HX0LxxOoc+B2x6FOCGZ2zPAX7f+3ob/DIQKd9GDg==,iv:CUGDa/ctk6RAbbqeVA0j4/C2Mmwkgc7Mvkolo7aaTuA=,tag:DgGTFSYFd8Jkud4j84skJA==,type:str]
    API_HOST: ENC[AES256_GCM,data:fSzWJTesKw==,iv:CHd5QbA2wq84t18tLMeR7DGgCeH/KAK1AbbA7C3Qno4=,tag:S+Jc79gBzPB4CD/+/aEWfw==,type:str]
    API_PORT: ENC[AES256_GCM,data:X9Gv1A==,iv:dgT3IHTfBuwDopIl5LTOgfBYmJPFWr4YSXPxnVj7G1g=,tag:1bv/gAyqLuvz+AnhlmoWgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eE9tUHZzSDBsbFIzckZL
            SFpzaXYxc013eGhyTWhSQlIwOUlHWkRiZTF3CndjWGlYNHFWRXgvWE9FTTIzSERZ
            MExIL0xHcU1JS1hFdEtSZTBOeVZQWHMKLS0tIGdjNVREYlBvTGI3blJ0ck5hVU9u
            WDdJbkc2MDdKTStYYlNncnpmTXVuWmsKUj4Vh/Xq+/T5SkK/ucLgfBBunM5jGh1F
            ZkwFSMR0+/g05CxRShSH3iPpaJiYexaVdFtmnLbglkJ8qaUcMkwN0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T16:15:28Z"
    mac: ENC[AES256_GCM,data:+LFNdGs+zOlh5IG8QfU9u+douE+Cp/uIa/YoE8+Guv5HM9rqHlPshwOlPxTZzYaQCxPQ3rBGy+4Ue6nLXffQRmRoxVR5pWP3coXmIk2m0KLE7cfu95oAQnYATBvF2Uhp8nKOUIJVipUIrv2AWxMz0kYBXK46DTvJTxdUNqee6Io=,iv:Eh44rWsPUbj/L7wTySVozZUygPdMEwjyRCiD/SMyLPI=,tag:Wuk/dh1bef8OoawKeXBWAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
