apiVersion: v1
kind: Secret
metadata:
    name: njdbot-discord-secret
    namespace: njdbot-discord
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:Ek+kJGjPfhS+VBOpX7K0aOPUYfeBBh6KuyAT1k2wgt0EFm6cJtYCRMS4iP5ao61fQ9sBQTEV7h0aVnzCr3lwuoNUtEbuDuYy,iv:4UuanwQ4fJtB/doAqsukndufs/KYQKbyyT7JC8bYWoo=,tag:l2YHmKwMjBs+FAW5nA9aYg==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:tuWsnLPdI0y1Pgz1obc1CFCALTWqXC3oR3dO7OV4OZuq1OglQkrWoH03+My4NH8wsyeHybAPfa0tZVqkFWDWRA==,iv:y1cv+Coit3wYxSdjm448akPPOfatQE0+I7MkV9y8zgs=,tag:3j/DLAekee/B56UTip+yfw==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:lg7ZUMCEoZn0dg==,iv:0TLBniXKVCLD5vnKSiG8zPPw8gHnmc5ToXdLzIjaOAA=,tag:qBTRvw19Hr0x48kbW7xPTQ==,type:str]
    PROD_GUILD_ID: ENC[AES256_GCM,data:S+u0WyhDGS1gAAdxm03/CRhFXg==,iv:al/G5lKtuEaL9Vh7R9w1qfGsocKre3h64EWv9+UA5CA=,tag:5NupeaPD3pgsXaBJawVU/g==,type:str]
    PROD_ORG_ADMIN_URL: ENC[AES256_GCM,data:kGAH3DbQF4/tz/Ep0YvuikOTMpo/+7zMjpU=,iv:1RPFt4NKxfvcCmJIs3tdX8f5N5QO2zDVwlsqsxCu8UA=,tag:pJ7KLMHEJ69hLHBg8fNj8A==,type:str]
    API_HOST: ENC[AES256_GCM,data:EEpejtiF9w==,iv:kmxKs4xvBxzTdXfLstckK9d91wu1dptiRJM2NbYL7xI=,tag:4NQQGF3cgROwyS0lqS5R1A==,type:str]
    API_PORT: ENC[AES256_GCM,data:RLwByA==,iv:zYcr9sOO8XSt3qxS3bfA7LtlGAO7/+R3v4DBeyGoYLg=,tag:NRD6ciaZQcbCcjzwhWkZpQ==,type:str]
    COMMAND_PREFIX: ENC[AES256_GCM,data:Zw==,iv:O38F7y835nokh7YYUavhEyHIm78vyNXZ8arDUHgrygA=,tag:b5/uLRi/VGCMa/JaX4G+Tw==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:kltR0g==,iv:/mVOxUsJSiYZV9rW4G+qcE3Q68MyfMXpEcoEmAv2oMQ=,tag:EVzFDdctLZ+mkFVaoThXpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZEJXWEhScm5hK0dhamhW
            R0IzalZhM1lWOHlDM0dqRjN5d0EwdE1abXhjCmRHZUJvNXZEdW12d2tWMGlNVU9O
            QjlVZjd5U1NrQ2hDeTVVWHRCM1hkQkEKLS0tIGlwZlVUZGlhWFJMK0Rrb2NIeGRl
            U25JOTFGT2QrczB2aG9Wc2t0d1BQQkEKPfjNCauBroi2luS9QsTqQnHv/JPyYmRX
            0RxYE8P6D4zGv3KUaCmz3oYnKb/zL8CjiLrC5FtT1qg1EiFhLPuTFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T13:50:40Z"
    mac: ENC[AES256_GCM,data:KlpaxMrc0MDBXP3Pr6q7mqpHHqHAx74z2bHjwReBWWW+Sy7sAhTLgNtcRI9duENYdUXejtg0rpL1/N0e6JzIDtRQIPHZvxLk5Zwxjw6ZREX+fU4BiMm/gKWH0NxGaH85NXRoCGPuJihtnwoSzl9wgH0tyP9DcmCN38tgmHyxJ8M=,iv:jsFb+WiWQfSInD1IChrzdxq+f3GMoRtJK/mMrFf7BN4=,tag:C22e+KYq5aOlQ1ktqkaZsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
