apiVersion: v1
kind: Secret
metadata:
    name: njdbot-discord-secret
    namespace: njdbot-discord
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:uki23empSS/ZFvb2p5KSgu627nQPRxHtg6odcD03Y4hSJBaWyEPcz4M/1qFFb0biXx1sHfh7Dk5jhib261/Txq1zNRzyskPu,iv:Qxnfx84Dr49m2ID7QxmO9g8tpflOVsuxme9QZB78So0=,tag:8E1i28TsxMqN6XenR1bV+g==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:pymwST6y/f4i5SCL5qBinlB070jteoJu/5sdLoomlP4wkgVbdGX67CxSBTzC9IZMPGL7GBCdb1AzifqNH12vrA==,iv:wRj1ZMSUuvi4H4YCB9qcgZ41adMMzLIwQ5Z/3lGUHmE=,tag:sxwaRIYbV5jrCKyuSgcTQw==,type:str]
    ENVIRONMENT: ENC[AES256_GCM,data:GDPSNBYtvPaG/g==,iv:fshh8U7GrE+qQ+osU4hX/enjzBzOzV+uWjwyoNeLgck=,tag:JuFqsYsIxm1auVwvWBe3UA==,type:str]
    PROD_GUILD_ID: ENC[AES256_GCM,data:X6Ret4v3oGwUqf/s8rt2ScEyVA==,iv:CrHmdDWOztW/7PoHt6rWjB7EkDRuJ/u6QklYP2A0Z0k=,tag:Vh4ES9th2AFybDbFEYLrqA==,type:str]
    PROD_ORG_ADMIN_URL: ENC[AES256_GCM,data:lKtcN9R7bkWutu+VjBxaBbvMGLdC,iv:9JxyI4RffUYpSE0b/b/sEUtBFv5BJqgjmpT6mci3shc=,tag:2GLXgCjpi23xEd2SZ9mj2Q==,type:str]
    API_HOST: ENC[AES256_GCM,data:9GhoDJNzTw==,iv:zPdZLjYXCwF8+/q/v1k87xKSqMKn8dHG8TZ7mWLJb34=,tag:eOyEf/xo77OwQGfM36aOkQ==,type:str]
    API_PORT: ENC[AES256_GCM,data:pY83wQ==,iv:SrSg+jF/B0pZKYoj+sXdlLqOyQUIkqDfNv+k+GdCPNQ=,tag:nBvM2r2e69Qkr6c85MAq2g==,type:str]
    COMMAND_PREFIX: ENC[AES256_GCM,data:Og==,iv:h3GCUF0vvfD14CItIsYpXBo5VWXs6oQClH4B3zioESQ=,tag:m2vzZwQc3u3RZObNmMxrOA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:TVgEDg==,iv:kwCBCTAC1/lJWuMrBOG72l+b3Ni8kkteiZrZ6c1hdXM=,tag:PwCo2dXTjAONYp/iOQKCiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWx6T2Juc0tTSW5MdXdq
            U0g0eTlSTTVhUmhsdkduUGFESVZmN3NKRERvCjk0NzRiOXZaL05HNnZhaGt4a0FR
            Ynpja1hwejFWS0dFTXRDSEVGckJYOEkKLS0tIGhJL2FsNlZKZmo1M3BXTDY3cEx4
            TFlLQjlBZnplSFlMN1Azc1JXeVRIUjgKZ401W8SCbiSfzj5sq8QmsuwEEbeUbdPn
            gY0KBFPpO5TADScIeqmPTMTW8P7HkyewcDjifPM7qvNCOW5TBB/5BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T16:28:59Z"
    mac: ENC[AES256_GCM,data:M5oi50VdGMCtQJJsdhW4ZNK/n/D88gxAeMS8HkjmSl2jpRO5RfwaBrZ+ZZ5XRH7BU+IoCNBYScb+0/BGf1pBeBqcjA0uTW+AD1VvB2wPcqbuNBl7sEFWq0HqwnYF9S3pFwLDzp8GogqhUXggh0Id6xr4MV5I7T2EvNE0NvMN35k=,iv:XXss0yww7dH0MQttbNxbrujZWp/af+scQj+Wg0TWI0g=,tag:1P0iDiGiqkeG8XXcx0h2tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
