apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: weight-tracker
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:eFtImoerQsaCh0QDbWffD87tg0BAIbmBTVvOoNP/QW1ssMoanfR4nXGG0/R0EaCpwsPXuiLtmiA5qqRa00dyTg==,iv:p0LbLi9eE3G9yC019G7NNqjdyNrLDb7T8kbMBdBcdMo=,tag:pb54jinJrGAcCpN0FwHmMQ==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:ltS8UdRMkmAFemLz9SUBNNIQWdUgsg==,iv:xnjHk53jB0+60GUYB2NzWnRJpuaa7bLJzedL1JTX4XY=,tag:FGmCQwVhyp+b14RW73URNw==,type:str]
    ALLOW_PASSWORD_RESET: ENC[AES256_GCM,data:7IusuGg=,iv:Oayh32m1V7OqtwRfQrvv+wWRFcxnguxOFi7xYn/VZB0=,tag:o17EqqHjJQnjjSAeJD98oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbkFXZDlPcWI3TlQ1TXlt
            WEZrMmduN2pDby9ESEhDeXBtZWNja3dMdXdNCk1zZGI3VUdBaU9QUFhaTGZ0VCtu
            UGR2bFkrNkdxZ2pMbXQxbFFBWG5DT2MKLS0tICtoZEVQbjNmY3FwM2NUbHdUeS9M
            bjh5b1YwcHVQWEROZ0puQmRab2g2c3cKJWxRSp/edrlJRisg8sj0qMCT7AZWOqxT
            hbnzy3LBfLlQx2nCjh6Ox+pRii26+OjwGOvWoe6A+CDNb2UYv4w1LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:56:50Z"
    mac: ENC[AES256_GCM,data:5PuSjo1ABHJ0DlfcEM8u6woBjaDc5Bm5p2C/49yQimFKFo42LoJP2bu1p61WRuOBqv7xaWRaPJCQjIoAKmciBi+RivVR6nGaemzDYhpxca1wti6VDOvwReCUjrl5gejcLDzLB6wbG+EMQFjz5LVvLzRAHCjhmbEsw6CnJgffHzk=,iv:76Mt7FOw4q5hgbr+dta1VaetUpX3QQO2h5X2pqrPwkQ=,tag:plHtfbMDn1stfcWIJsoqoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
