apiVersion: v1
kind: Secret
metadata:
    name: naja-admin-api-secret
    namespace: naja-admin
type: Opaque
stringData:
    ENVIRONMENT: ENC[AES256_GCM,data:oC/n+W63NgVnCw==,iv:nc36Y6s2SrblVDTgyzvfd8saj40r+ngnoKOMdvuKkj0=,tag:QQuIBWabhVGrQNyHD53uuQ==,type:str]
    DEBUG: ENC[AES256_GCM,data:HEo+fwM=,iv:2/U+5gDL3KuAd33HnRlE7mZlYjKZikyIJLic1T5TksU=,tag:kHOrDbwEj1nRb5XIwkEjbg==,type:str]
    APP_NAME: ENC[AES256_GCM,data:baZtyOWMa7sq1g==,iv:2p/qIYf5vawLV4Rzg4IKRV1TU0BtleGSppcXmYaJsOw=,tag:nrEKJG2Bbbg1JjnpXNUN4w==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:t0fvyVE=,iv:KAgrhj+0r+fpbIoBg+zYjwNf6PRR9PHjTs/he+GBP+0=,tag:B+slg5bQ7QeMyngP0exOVA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:UmgRjatLORH6WWZZRog/IsFHa6e0FrDU7TGpof93F7MY4dOioiL9WNJxUfkqKorhdzjti/szyoIdICdlXZq9ADqFF/HBLx+xGl0fwK4Xr2+VB6lUxf/rgrdD3YcPa1mDlntUCdVSfG1DyfFFbQkfqtlsVg==,iv:Z6PXXFCn0lCchx/Iy9ychXk6Bz9z1H/xqxtaPItoGLg=,tag:bcKjTp+6esIzvfGdOucpbw==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:tb3grBOpI7tHQXpcjSlpgr1LEw==,iv:NG6a1+YGhUPtbmAGfRmMIIhM2s1wJHyUo2bH+BVxb30=,tag:O0vLtW7VhcKteznWpxATHQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:X8p0t2eHrl8DKazZ/vG2KPQXiWLkBXirXAj5XM2p1LQ=,iv:soFIRs2U0cdEraII/BIfBQ8RwfGB7Xs4s+5aDwjkDq4=,tag:wTZbBQX0ZzGtLYFddPyAGw==,type:str]
    DISCORD_REDIRECT_URI: ENC[AES256_GCM,data:nNFAUyFj3RcWSZgmes51j93Ro/Z84p4VKlb+14CmtiM9dDrw9uyhkEnHsyDjNjiayzAZ/V7E3xA=,iv:OGhIc7Bx6dUXwKwE7WCnVdQmP+mf2sDMCWjvK+l6xg4=,tag:aC7uV+/3wrbkIxt7EN0JwA==,type:str]
    DISCORD_USER_URL: ENC[AES256_GCM,data:WpVYVfKMXE8d4RZGh+iw+GYOtqCI+oCxThTOyLkmMAOq,iv:tzDFgSNUs+IWZrY4BvYEQMBZZtufGH7saIsi4sEG5Jg=,tag:YaEZF6asRozmYPPf5oFpRw==,type:str]
    DISCORD_TOKEN_URL: ENC[AES256_GCM,data:zzU4r4qfMCMM0ExmgZbCeObkLvyuyKUhoBaJx1Vi3R9rje8p,iv:zn4Y3U7AeQ3gVNZIuFWhvGmwvhULoDSTZ/uvlYRzpEY=,tag:SWuGakZoyDS5VjxHZHemVg==,type:str]
    TARGET_SERVER_ID: ENC[AES256_GCM,data:zUox7EHxIMZg+NdHmDwcp714bQ==,iv:b7KTg4H+9SBVIQLdES0F4DrRx/Jy/xJfKI4GTJyleSo=,tag:dUojLL9n++Fz/yB39vFgUA==,type:str]
    TARGET_SERVER_NAME: ENC[AES256_GCM,data:BV8DlTrdjQ==,iv:5Syg1Pqa7C+GNbV0Sh8jbNzCM00WFSlJJaQOGexy3WE=,tag:lB7iCv2ynGlHeYBuBWF7XA==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:Pt1fFC9FuXeZSmXz2dr8FQtsC9dGRnnfXmPdc18ZeC7mZPEUpjGANnLIpebZHA6eZv1052nBvASaHVxbMpWFTQ==,iv:Au6vGSMU99ZhQjev/QJcPWcFzrjzyOHSVoUJY29TNEU=,tag:9wVff9L4k8kISQJWT27BnA==,type:str]
    GIBBS_API_URL: ENC[AES256_GCM,data:+WYF38MvCU1yv1pkxwhl62F4s+GJbtYi0iCjy1dVMhXRyJNL2d/IHZyYDdmmef6zFqScwuPGnxydxsBR0OGhY32kkA==,iv:/iRbDsXrKjEJnwx9pl9qL4UXtLDyJkWNaZMiaBNuV6E=,tag:AeiZNqkVkdvdFjv7kJjkKw==,type:str]
    SC_DATA_URL: ENC[AES256_GCM,data:BlnjVrIxjFzjxPKvMls+XO12X0/L3aobeRXsS3hKknMwpFAdFLJfG7yOELFvwU9AWXy6,iv:Xiz38CovPi7qzRh8Wu3Ak8WS2cwQGHv6RNWkojidMGY=,tag:t/s8tYbI1m1Z/bNzZs193A==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:k1drdcfV7G2x1mq5nFPdeqpTzJ2FPBk1umU=,iv:SWp6kL7EK8Dk/H6RAqZZyCNGFWlbpK4VBHAe4lnBn/E=,tag:Q7mbC67Lnm1ZAmAD+JpAtQ==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:6SqooxltovBwhIlYfUZitV7Zb1+1aSVot3A=,iv:3+XslKDbjivNrW8bbRH4+TFlDK4bSI3PYVMiTP5WcCA=,tag:yi4Ep6EGGFvCubQtdV0mBw==,type:str]
    SESSION_CLEANUP_INTERVAL_HOURS: ENC[AES256_GCM,data:VQ==,iv:Q2nFbImEsauEgyuZC6earaoffiL7G8I7k2LO12QDo8I=,tag:AHGQcV7+7E/l54vX87+M4Q==,type:str]
    SESSION_LIFESPAN: ENC[AES256_GCM,data:SQ==,iv:nW+6+6SDQuBcnRYq917sJ+t8S0dv9cWQo4WnBAPuiq8=,tag:j9Nn7MzJUub9dOnFeeKs5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobFBQdTI5YkdTTkhuMzU0
            aDVpRmdVbEcxbktEcjkrZTlrTUxPb21JdURJCnlEYTdlTjZCVjBVekdqZVdRQmV1
            ajZWb2tadjFFNmVXbkhIRksrNTcvN1UKLS0tIE1HUGtETGNWVDdiRGdib3lBSWk1
            TTlsYXJ2SzFYS0ErOUpMbUxPZW1HR00KV3vNU57HiTB9dWkoagfrvyhzPA52eQkp
            e2D5DmWqiygtrnr0wE/eeZrmWutyqFRy5i+nt1isj+hWCKcpveDYgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T15:38:33Z"
    mac: ENC[AES256_GCM,data:Ldo7GpIOze48QBHcS9y4b4aAXDgeBBBgbx2MbF8OVwCfFQLMpIDhadchjGUHhmOuoBkte4ZzV6v4wfIf4O7UJnEKuoB12j9ILm8WZuyUX2qFAfa980KaE8nJftTk/qhHq5oDQbAsTgxr53kCcuXBrZ1w4+YFFR2O9ORxasG9H7A=,iv:K/q0u16U2jp8nIlbdcdzRQFExT9o/Jwh4XVz3fzJdmA=,tag:xsU2ZQFpk+26ZycA5ZipgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
