apiVersion: v1
kind: Secret
metadata:
    name: naja-admin-api-secret
    namespace: naja-admin
type: Opaque
stringData:
    ENVIRONMENT: ENC[AES256_GCM,data:J8LioBHtiBvz6w==,iv:0EJArDG14PVOTYCLvaLLtaHIKizVBjo6jFnQw2CKjbM=,tag:zZ97W55IPRdj/+WkhjSi6g==,type:str]
    DEBUG: ENC[AES256_GCM,data:Ixd08O0=,iv:tJKM9zbRFuKD2Ef9wR5tTxTiro/fafJQ7NHV2a2M4Hw=,tag:WDbHo/jSFEsdQ6J4efhXvw==,type:str]
    APP_NAME: ENC[AES256_GCM,data:QC9e4zgwQ4GLhQ==,iv:QEfNixsD/F+r6fT9f3PMA0C64m5dniEpiUd+GlfdDPQ=,tag:zfiY4iC+8bQrrkqgT40C4w==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:z/OMLl8=,iv:BinqJnD3vOoGdJubiDTDt9h48k6nzgkznme7RA/FqlI=,tag:G5LBqajd885NZty0a2YMlA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:d7pwAhlO7i3hyrICgRPSx4jhvf01m1TcDVTjsSSPoSMGXGiDaKSIMX8UkRscLlG0/2/ZlEeR1eaie7wZfDw=,iv:YaTV4PKTw//gMpTd8r8oAr1BVzXTBsFml/TA7JOOU/k=,tag:L7y/liBnBtfbKnfHsQDbog==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:PWgUJw==,iv:qmdE3Xn1DxS60yB1umfeD13zrVL533znvmiQ+ZMpYhQ=,tag:TGpZO+HcGUfmesPrEhXaMw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:Cepf+Cvh9xY=,iv:7d3kRoBOi29D4oD6pzftMhxpDkH3jz8IZDn0OjrTqb8=,tag:Hl7F85WhE8pS7K1a693zwA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:o5hkX0qlZvXImmOs,iv:LC3KVzT3RFIbQn6Azxr4aobEvYUijHDnmhtzJmTEYRk=,tag:S35xoc8g1YbNbb+fJp4OzA==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:92qvQN0kIYqXNw==,iv:TNPWMVIVffU43mBKcibhnMAnG6LrU2dqd4SAsEB8tcc=,tag:N0ATwbKI+Pd+rZuV16xWKg==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:6Y2qrYRehztDCFHGbWSdxydNCA==,iv:QRnmkSLNDxv+refmJvWYhJ8fTW048P0WmqbiGyZRx+o=,tag:sNdEJO54SewrsKJd7r6ayQ==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:dz49+DknPBn+EgbYM4yH6GmgxWCh52PxIl/fFOTm2P4=,iv:oKpzdj/O98mizP5GpMDQtQik/ER5kVSktVUm6YOVLMo=,tag:5E2NqPRA3IUr+iR/Nv8TaQ==,type:str]
    DISCORD_REDIRECT_URI: ENC[AES256_GCM,data:CMIbxyeFjdnWb6J4acl5IdjHMgl1h0ng6ZNpVtQlt8fmSA9nYF92X+lK7ZdNxdKKZrfrkZkhIHc=,iv:7G1149D+cHnXd3+m771BisvIfshUsS05xWjVqvviBNU=,tag:8IgOdcLeT3wn2yOBRTbIbg==,type:str]
    DISCORD_USER_URL: ENC[AES256_GCM,data:PyX0gKUdf5eVwp2RIA7rGc434dP4whDOwlLeqFLgocWE,iv:WeMsatrH+dRLwB4k/G9hqfU01RO9JVGEhWuyeyLVUXI=,tag:9pe7g5g5WpIJ7W7j5enpEg==,type:str]
    DISCORD_TOKEN_URL: ENC[AES256_GCM,data:dOTsFv74ZuEnnLtXr/6z7tpxWiZ4Uz9Y/zJ6tr/d/JwBB4YN,iv:Ic5JZJ5SDgAuh0Yelj38GMuLRmns1uf+jhoAiV5fuXQ=,tag:wbhL5o5tpant+eU92NcjKw==,type:str]
    TARGET_SERVER_ID: ENC[AES256_GCM,data:Xmv/New1aAahd9FsAyZ/3mSPpg==,iv:VuhvWxJiV8FLnOsGMmHHjwvbYzjokDz5ifPdnOOQ//4=,tag:j3aGAGytbywKToIHn9os6w==,type:str]
    TARGET_SERVER_NAME: ENC[AES256_GCM,data:TOOyFS27Tw==,iv:+VBUGl1urOxaPLhW3c6STG1YDyaVuEoaMKhxRZrawHc=,tag:9fvlm9TcFncD5ryyC/fyFw==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:at7MoENSmFBjTs+BmVAzRnagm+9MfkUVlw8dJaiKLkDWfhbDw50qKUMKwml6OMdh+N00dHJuOXlfJXQ7uDBOqw==,iv:huKkp4o1XYiDBRkSuW1Ka2OF3cvHRrMveo8L8SztjWE=,tag:l7BU7bN20xqbd88smDSfRA==,type:str]
    GIBBS_API_URL: ENC[AES256_GCM,data:BhOwu3C8JKJPxUpbA6XtaCoyfHpq8VaWN3Ma+WRtX4/SROYeeqopbKE3LhbwisrqVkIUK7neh+MaDBTkF3LnghgoYg==,iv:+9CNEL/3HygHSAZvKzZbqnugv/w1Qgtj5LG3k2zV03M=,tag:y2yDZkUJtniHdS5gYQOBIA==,type:str]
    SC_DATA_URL: ENC[AES256_GCM,data:CetJRwqpDgHr7CGDWgilGxM7HIs8KtRf9Qa/ix8AKH75dyRoBvHSdjnRB+UdrVuED5vt,iv:w8A5wcpPVp51Fw2pXb6Fk897WO4vUdQn2xCV0fIiHFE=,tag:rcXl4uit21C/rLFW8XwaJA==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:diwFeg/l+dRogZLs7X7HIqKcnGBmuRFAYPk=,iv:L7wQLHBxfdnejETQu7J8Its0Zh5K5BVt0RBBI6WpEuY=,tag:2wvdYTMVxmqdfAyUAfENtQ==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:mAyP2dh0ONUmqijyTGmUjZP+foujD5a6BUU=,iv:k0Gz5wrYWqLniG+9au87FqLRCP7RkITzV1CtBhpDf/Q=,tag:GQpvk77brt+wv5PJK8i6xA==,type:str]
    SESSION_CLEANUP_INTERVAL_HOURS: ENC[AES256_GCM,data:tA==,iv:zoowUPZPim6LJwCqS5PBGUt9dKNEsxoZaOJPjzflRrg=,tag:8aB8gyc+R497rVfYp/tNVQ==,type:str]
    SESSION_LIFESPAN: ENC[AES256_GCM,data:DQ==,iv:OrEU4K88ojfLRLCSSKLFlJXV0qtNHKQ3QLDpSGupfQY=,tag:Bd6UXyAfoWxpidZ4KwP3mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbFI3OW1xVm04MTZlZ3Fh
            T3hQcVFzRTl2dGFIQlVaNXRLa3R4MmFwbkFvCm5ORnZtclU4UFBSS1lpWnV2aE56
            cit4TitacnVmeG9HNU1wdk53dk9TdjQKLS0tIGh4SE9VaElEQkZTNHFsZUFVR215
            RGxTNXlodnprZFV3eENHK2YvdnA5M3cKdO8ecmO0siAbu01xXcO/tfNDZVcuay9B
            ui3Ce2wnf4t4iBN1coETE+3+/EXZR5ZQz/xM8tYnoeLwArI7x23Sxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T15:45:32Z"
    mac: ENC[AES256_GCM,data:0GdxwKKhxdXTEsiKuXjjt2308/c56tAsuABaZc/852VDRJZUGW3UcVbwkZjrnsFWTH9QUDhqsaCY1wMCeVYFNd53lcoAfcmhwFpOOa7v34u0xLqCfqGUs7U/9DOz1fypf04cwPh3hIkukTJDS/WYQ0jX4yK0voQ+BHLU2mIjcz0=,iv:YBrACsv+yE3F5rOL+qFk9OXTsqhwbwD/gCeH0A+gO3A=,tag:y24gGE1LUey/98wRonDRIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
