apiVersion: v1
kind: Secret
metadata:
    name: naja-admin-api-secret
    namespace: naja-admin
type: Opaque
stringData:
    ENVIRONMENT: ENC[AES256_GCM,data:+ZGmeEmbEbGKPw==,iv:DIuUtYBgj+pIs0hV9bp8S1CMd9qo7ivapdBjGv9Hu5o=,tag:xK83/Wyg8IQgyaYx6xUU1A==,type:str]
    DEBUG: ENC[AES256_GCM,data:vjypwGg=,iv:7q9l7sGGML81Sh2gfqBy6SQ47MhhIFqACa84ng4wHuE=,tag:eH2J3D2NWxkwYCIqxarU/g==,type:str]
    APP_NAME: ENC[AES256_GCM,data:n+LEkgFduveP4A==,iv:jN06YDLuin1luuKTTPXfuyy9thwYSYOVn5mXIace2Os=,tag:oxzysJWHrnfDA6d6QxeNGA==,type:str]
    APP_VERSION: ENC[AES256_GCM,data:DWuARaY=,iv:8y2byGLLTQfHL9BXMxVG8Ns5KNwM0Wata5Idn9iykyU=,tag:heKyHAL64mpqZB0Ra5Rb/w==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:r04Tk5xHiWJrNuIG/DEQAPI2c0xorV9WemVZGAFfyhhWw1AtqrO+sukPnKchPEXQbgXqyYhE4SLZ9Qel2aw=,iv:3heZnG+Aq3NsJZkNoqQ1kJD3jKy0Wl39vQ86Sv1oD1c=,tag:rlbEFvXBoL34sFPeoH8lSw==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:XgjAOg==,iv:7v6Vtg4RJt88YwyIJt4g5mznH0B1FZ8cakfth3cqwzU=,tag:LpT3RJSm5z9223bGqGV6Gg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:HXBTMwiNsCM=,iv:RSxVJ9/FwHFiW1eozkZPMDi9Sm8+1UKsRMvMUnoileE=,tag:X30+Vdmc686aJ9ylFRem6g==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:/kSDi6wo5i/FbqV0,iv:dd2SxyiqIFFsqZvoEl+w2IZEEh8IXMCOym9TiCc1XqA=,tag:7bbJ+SYz9Ojs5+vmRLuozQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:TIPjYLpYMzRnrA==,iv:O48R3BU2h54gjVpVwP3UAQbF196YjN4R1IoM/f71E04=,tag:a0nXmiJAAWpvX+j5Ozt2hw==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:horxBlLFWb7RrteiN1h9xQncZQ==,iv:reRc6TaArHbe0l0JJiwpjKHy7IeSittWLmnKlOfHIIc=,tag:huw7T10F1qeTr3tZu2UECA==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:lIkq1TCYE6y1bIvpS0HqyzFKVu0H7N9MUz7UTLpY32M=,iv:To1wIMnL49bqopfdh2Tns9AQKa0F4bEcSzMCJc+VXQE=,tag:CtSNOhT5gEXEa5Ryo9MUTA==,type:str]
    DISCORD_REDIRECT_URI: ENC[AES256_GCM,data:zXBXyytTCQqNYE869P39g6H8q6olqwVCsrcphJKNkJAQDLy4bNoOmuCVfHyD+56+cmxG9D64EVs=,iv:Y05XAV7IQq2qpiFgSWzaIeuK7g22KQzBak90LgzxrPM=,tag:JkxeThiLcSEJrKxJJ77GAg==,type:str]
    DISCORD_USER_URL: ENC[AES256_GCM,data:UeAuwSq3//RF2oidn710yY/TPGpH5YCcyATu9SMxrQDj,iv:748WzG0YgGAPKy8IixYdTLcy1WqesxvVGFQ87A875Uw=,tag:nIG1WJQWZz1WRwgksYI4kg==,type:str]
    DISCORD_TOKEN_URL: ENC[AES256_GCM,data:uobtoorjX4az/UpuyvtegNp+dADoROBAYQBPA+Hp5uf2Qb6M,iv:3AN4AREFEWbkZAyWP3TvezmvYBHKLGsb6V7m3uASarc=,tag:CqXQQD4gvHAwb71DqQKE1Q==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:+iChOCbGwEzFV5XZen5dy7mGrLEAQMBUxHzUysKVVknovdcai3l0RLu62LkBGqyY7NWlTPH8S+AgDpGA7EypGs6vROy1uDVf,iv:kF83aek0WF00w1W/VE3EeAmm727nd0AOEO5la/jOwtw=,tag:LQF0YvXvaBDn1ql1MKkf2w==,type:str]
    TARGET_SERVER_ID: ENC[AES256_GCM,data:wiwCYe4UAVC1kIjeWnCuw3EUaw==,iv:LeSKh2VGlrxNVGsmY83szi1html96DeZxm7TMmeoprk=,tag:2Alia7fEwv6spvOvuckO3Q==,type:str]
    TARGET_SERVER_NAME: ENC[AES256_GCM,data:kIBL2kMOmw==,iv:e3zxl6E4qc7rkYoYeDkfB5TKigO+66FhmAlxbkunM7c=,tag:BBHzL1BOZLPj0D/sH/vmhA==,type:str]
    BOT_API_KEY: ENC[AES256_GCM,data:fgYHCncDhXNRm0C0SSCrBLjDzDtYtVYrzHhkF7mheK6fz6zRP6fNA6Tu8fB5cTjJ9e45sKa7n26t1hl6XcFGbw==,iv:nTqcjPUr3pQrNiZGFnRPAW4ShKp9bNjnEmnfcLpy330=,tag:cesomKSBU+CV0kP1N/gx0g==,type:str]
    GIBBS_API_URL: ENC[AES256_GCM,data:p172hFbDYaTe0h3sWe6Wj/Tgm4s3DzOZP9jGqhSLkn0+MECrnVHZN8W18jSNZq5/g9vD9zzm2/PALJz/ac0jADY1zQ==,iv:jeuZwNp+PnbpEDv/Di/kbZI4XBPdi5/HpedAzFBeiuc=,tag:J/672uE3NiBxdQDk3Yd2iQ==,type:str]
    SC_DATA_URL: ENC[AES256_GCM,data:/7dw//THkGfY7mo4S5upsxBCA73m+PRDGPf4HnLlLIOQZBIsNAqtwVsngNvN+EHC1TTW,iv:jYPoDbzj5vDggfAlmCju1yu8Rpz/TxC2DeK3xbYqXf4=,tag:PpoWe0ty5Bo1O/I4izq0OQ==,type:str]
    ALLOWED_ORIGINS: ENC[AES256_GCM,data:y1I+/GJmKNSUZW3ZNQL4igNqP2kxl8G+gE8=,iv:/bu48ZjbvVv2YDPtjw2L19Ba0zVbncyskiOIJyCTrtg=,tag:YT5n4wIqtNA1OaMw3mHyIg==,type:str]
    FRONTEND_URL: ENC[AES256_GCM,data:O83R0d6ja1TWCxy9KEfAOAl92oStQKvha90=,iv:O/ltpJtyJkzv2ySPQYv7/ZE11MfNaD+g2OWLWWDjRDM=,tag:JEPR2l61LIAdx5KqFO19TA==,type:str]
    SESSION_CLEANUP_INTERVAL_HOURS: ENC[AES256_GCM,data:kQ==,iv:kiqNfsicz+T1M+dbSGjOsm3caTpjjyj9MlUQ9ki4W2o=,tag:k3x8jzsf4r7LU/wvA9EzdQ==,type:str]
    SESSION_LIFESPAN: ENC[AES256_GCM,data:Zw==,iv:kopHmWKE8Gpgtc0hoPeSYNMZLAyP4PEfD0E2p0L5Hhg=,tag:2/X7KgBzURDqkBPvgbeIBQ==,type:str]
    COOKIE_DOMAIN: ENC[AES256_GCM,data:SN6zL337adwp7P+ayjc=,iv:gphpk1aw78gfmlOeoBlyiC+HhR4LfVeK79x5EDgcLQg=,tag:OyUcu7iPbT4CsNQFDxh+Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3VRbWJOOTg4Z3VabkQ1
            dytJTXFzMHFSQXBkZmM1am1DZms3MVZ3TTNvCnBzZ05tRDVJbXZLYnhjNkdudy9y
            aXVDSGNwUzdyTXRNQ2g3NTdSRkRCMmcKLS0tIDIyUEdHYkgyNlcrUmp5SzZxYmRF
            ZitOeFhObjVXT0JGSnlobld4Uk1xY1UKR4sXWPo2wbCzO/3tMgpK32w8whU4BMeZ
            c7aG/Ske7fhBO5OwZx5FX/OVflhpoq16diD9Ql2b6pwRVmM9XyKzdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T20:46:14Z"
    mac: ENC[AES256_GCM,data:xgYs6FTk7VoYaLDos8m6A102f1c7awjx/kGTXQ7/ybx+A/JJ1NKu0uzVrZZSHJw0h7e0SIF2K0wza+NIoSJS8897ox+EhJHJ2P+/IRhExPIeiKp2ZCuhi7/p/w7c2q4fHNLXhV1LChFxQwUtHSZWqj0cJuFwa/VBdVsFhKLa8Ys=,iv:4kGwK1WcOQXdEJ8mc+Gw+JvTgPR7YgAieZFm/A9JQtc=,tag:ODFaoTCCA59y+Fu7EpW+Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
