apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  releaseName: minio
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "12.8.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: minio-secret
    defaultBuckets: "plane-storage"
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: ClusterIP
      ports:
        api: 9000
        console: 9001
    metrics:
      enabled: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
