apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  values:
    ## Staging-specific controller settings
    controller:
      # Use a single replica for staging
      replicaCount: 1
      
      # Staging-specific resource limits (reduced from base)
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 64Mi
      
      # Ensure NodePort for staging
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      
      # Add staging-specific annotations
      podAnnotations:
        environment: "staging"
        
      # Add staging-specific metrics settings
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
            prometheus.io/environment: "staging"