apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - release.yaml

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: infrastructure