apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/postgres-arasaka/namespace.yaml
  - ../base/helm-repos/bitnami-helm-repo.yaml
  - ../base/postgres-arasaka/postgres-creds-arasaka.yaml
  - ../base/postgres-arasaka/helm-release.yaml