apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/postgres-arasaka/namespace.yaml
  - ../base/helm-repos/bitnami-helm-repo.yaml
  - ../base/postgres-arasaka/postgres-creds-arasaka.yaml
  - ../base/postgres-arasaka/helm-release.yaml
  - ../base/postgres-weylandcorp/namespace.yaml
  - ../base/postgres-weylandcorp/postgres-creds-weylandcorp.yaml
  - ../base/postgres-weylandcorp/helm-release.yaml
  - ../base/traefik/namespace.yaml
  - ../base/traefik/helm-release.yaml
  - ../base/traefik/dashboard-ingressroute.yaml