apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cni/
  - ../base/postgres-arasaka/namespace.yaml
  - ../base/helm-repos/
  - ../base/postgres-arasaka/postgres-creds-arasaka.yaml
  - ../base/postgres-arasaka/helm-release.yaml
  - ../base/postgres-weylandcorp/namespace.yaml
  - ../base/postgres-weylandcorp/postgres-creds-weylandcorp.yaml
  - ../base/postgres-weylandcorp/helm-release.yaml
  - ../base/cert-manager/