apiVersion: apps/v1
kind: Deployment
metadata:
  name: admirals-log
  namespace: admirals-log
  labels:
    app: admirals-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admirals-log
  template:
    metadata:
      labels:
        app: admirals-log
    spec:
      containers:
      - name: admirals-log
        image: ghcr.io/omtut/admirals-log:sha-f6c55e3d868d749beb3152f45164177958cb9b6b # {"$imagepolicy": "flux-system:admirals-log"}
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
