apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-cert
  namespace: searxng
spec:
  secretName: searxng-tls
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - searxng.wc
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048
