apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: admirals-log
stringData:
    credentials.json: ENC[AES256_GCM,data:NTGmsT23AZx1uzUHDL08tYMZfrwB2Iy3u22Y03ajT/sGSF2eFGZ2cFBGvM178cnGxV8PWMcMXJenvgQBCcQpeGbyjOVb390VqBOBYrgwAxwoFucWCPbzgoXp0IqcUYLd8RXuvIxQEAZLs0CFm2ABl9KIyMrgLeylZh9RVLqcScAX3ru4utW/M6fkmaKb1unuwDCV5JtkiHqjqLrlli+RFL+RRrh6Q0YX1RkriMne/72apPDHZrOQF4ssii4I,iv:UdRQCQGkBap6peprXAIHJGf402/+JEg1ZikP6ZgTrH4=,tag:K8hAXk0JbIAyELMCr20inA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d27ez6fmsuq2x5j42sqm4ldqre2mgxksmpq0y2rrhr4x6hfm4yus3qz34s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NVBsRlpzaWQ0MnZqQkhj
            elRzd0FtdlQzWGc2N0ZUSG02NWVyUDY5NXpZCnhWT2lWVDJOY3Z6a1k1TEZkQUMy
            M3l3Q1ZoS0NTVWc3cGpSQ2E1czd0NGMKLS0tIFRaOWJRRXJoT1dCUkFwbjFwVVFx
            Z2VIdUNuMEVJUDZGSWg2K2xlalo1czgK8u8SdxOI9vQaBtyjSCt/FL35Zbf1PbB6
            +bY7ABcln5PXyujRVCYbWGMXC8SP1aSgl0AvoA7KanY7y/BjYx2dwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:22:05Z"
    mac: ENC[AES256_GCM,data:tSjstMFpQqFJSp0aZcJW4bNqLhPREwdD/o7jRfZCSHOOclmEOwqfAFL/lAxkmEEeJTjOYsDBo6cpvNhZq9ruHryaJzzHRnwVdofYcnX6UTdiRZcMIZr2JX3+qY5KsMrULZ2ciPJx3Iyq/k0W6IgLlwgQytaOHWghL7KfIpjcd8M=,iv:ChmzKsBZ0ePzjbVVC32f2WJOsAwo34+QpadSIIMo1ig=,tag:qCjMYH2HAlaLxea26luN5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
