apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ld-psql-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ld-psql-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ld-psql-secret
                  key: postgres-password
            - name: POSTGRES_HOST
              value: postgres-arasaka-postgresql.database-arasaka.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-container-env
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-container-env
                  key: LD_SUPERUSER_PASSWORD
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
