apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: rjt-web
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service for internal DNS