apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: rjt-web
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 300080
  type: NodePort